services:
  application-server:
    build:
      context: ./backend/application
      dockerfile: Dockerfile
    ports:
      - "7000:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      ENV_SPRING_DB_USERNAME: ${SPRING_DB_USERNAME}
      ENV_SPRING_DB_PASSWORD: ${SPRING_DB_PASSWORD}
      ENV_SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      ENV_SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}
      ENV_JWT_ACCESS_EXP: ${JWT_ACCESS_EXP}
      ENV_JWT_REFRESH_EXP: ${JWT_REFRESH_EXP}
      ENV_JWT_SECRET: ${JWT_SECRET}
      ENV_APP_SERVICE_URL: ${APP_SERVICE_URL}
      ENV_APP_ALLOWED_ORIGINS: ${APP_ALLOWED_ORIGINS}
    depends_on:
      - postgres-server
      - redis-server
    volumes:
      - pianobear-app-data:/app/data
    networks:
      - pianobear-network

  frontend-server:
    build:
      context: ./frontend/vue-project
      dockerfile: Dockerfile
    ports:
      - "7001:80"
    networks:
      - pianobear-network

  redis-server:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - pianobear-network

  postgres-server:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${SPRING_DB_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DB_PASSWORD}
      POSTGRES_DB: pianobear
    ports:
      - "5432:5432"
    volumes:
      - pianobear-db-data:/var/lib/postgresql/data
    networks:
      - pianobear-network

networks:
  pianobear-network:
    driver: bridge

volumes:
  pianobear-app-data:
  pianobear-db-data:
