services:
  application-server:
    build:
      context: ./application
      dockerfile: Dockerfile
    ports:
      - "7000:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DB_USERNAME: ${SPRING_DB_USERNAME}
      SPRING_DB_PASSWORD: ${SPRING_DB_PASSWORD}
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}
      JWT_ACCESS_EXP: ${JWT_ACCESS_EXP}
      JWT_REFRESH_EXP: ${JWT_REFRESH_EXP}
      JWT_SECRET: ${JWT_SECRET}
      APP_SERVICE_URL: ${APP_SERVICE_URL}
      APP_ALLOWED_ORIGINS: ${APP_ALLOWED_ORIGINS}
    depends_on:
      - postgres-server
      - redis-server
    volumes:
      - pianobear-app-data:/app/data

  redis-server:
    image: redis:latest
    ports:
      - 6379:6379

  postgres-server:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: pianobear
    ports:
      - "5432:5432"
    volumes:
      - pianobear-db-data:/var/lib/postgresql/data

networks:
  pianobear-network:
    driver: bridge

volumes:
  pianobear-app-data:
  pianobear-db-data:
