services:
  application-server:
    build:
      context: ./application
      dockerfile: Dockerfile
    ports:
      - "7000:8080"
    environment:
      SPRING_PROFILES_ACTIVE: local
    depends_on:
      - postgres-server
      - redis-server
    volumes:
      - pianobear-app-data:/app/data

  redis-server:
    image: redis:latest
    ports:
      - 6379:6379

  postgres-server:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: pianobear
    ports:
      - "5432:5432"
    volumes:
      - pianobear-db-data:/var/lib/postgresql/data

networks:
  pianobear-network:
    driver: bridge

volumes:
  pianobear-app-data:
  pianobear-db-data:
